arch: s2t_ctc
encoder-type: pds

encoder-embed-dim: 512
pds-stages: 4
encoder-layers: 10
pds-layers: 3_2_2_3
pds-ratios: 2_2_1_2
pds-fusion: False
pds-fusion-method: all_conv2
pds-fusion-layers: 0_1_1_1 
pds-fusion-weight: 0.2_0.3_0.5
pds-embed-dims: 256_384_384_512
pds-ds-method: conv
pds-embed-norm: True
pds-position-embed: 1_1_1_1
pds-kernel-sizes: 5_5_5_5
pds-ffn-ratios: 8_4_4_4
pds-attn-heads: 4_6_6_8

optimizer: adam
clip-norm: 10.0
lr-scheduler: inverse_sqrt
warmup-init-lr: 1e-7
warmup-updates: 10000
lr: 0.002
adam_betas: (0.9,0.98)

criterion: ctc
post-process: sentencepiece

dropout: 0.1
activation-fn: relu

macaron-style: True
use-cnn-module: True
cnn-module-kernel: 31
encoder-activation-fn: swish

#load-pretrained-encoder-from:
