arch: s2t_dual

asr-encoder: transformer
mt-encoder-layers: 6
mt-encoder: transformer

encoder-collaboration-mode: parallel
decoder-collaboration-mode: parallel

encoder-league-s1-ratio: 0.5
encoder-league-s2-ratio: 0.5
encoder-league-drop-net: False
encoder-league-drop-net-prob: 0.2
encoder-league-drop-net-mix: False

decoder-league-s1-ratio: 0.5
decoder-league-s2-ratio: 0.5
decoder-league-drop-net: False
decoder-league-drop-net-prob: 0.0
decoder-league-drop-net-mix: False

share-decoder-input-output-embed: True
optimizer: adam
clip-norm: 10.0
lr-scheduler: inverse_sqrt
warmup-init-lr: 1e-7
warmup-updates: 10000
lr: 2e-3
adam_betas: (0.9,0.98)

criterion: join_speech_and_text_loss
label_smoothing: 0.1

dropout: 0.1
activation-fn: relu
encoder-embed-dim: 256
encoder-ffn-embed-dim: 2048
encoder-layers: 12
decoder-layers: 6
encoder-attention-heads: 4

decoder-embed-dim: 256
decoder-ffn-embed-dim: 2048
decoder-attention-heads: 4

#load-pretrained-encoder-from:
#load-pretrained-asr-encoder-from:
#load-pretrained-mt-encoder-from:
#load-pretrained-decoder-from: